config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  root 'home#index'
  get 'trainings/looper'
  get 'measures/looper'
  delete 'trainings/:id/delete' => 'trainings#destroy', as: 'trainings_delete'
  get '/trainings/:id/delete' => 'trainings#destroy'
  delete 'measures/:id/delete' => 'measures#destroy', as: 'measures_delete'
  get '/measures/:id/delete' => 'measures#destroy'
  get '/trainings/:id/edit' => 'trainings#edit'
  post '/trainings/:id/edit' => 'trainings#update'
  get '/pages/sobre' =>  'sobre'
  get '/pages/regras' =>  'regras'
  get '/users/passwords/new' => 'users#new', as: 'forgot_password'
  delete '/users/registrations/:id/delete' => 'users#destroy', as: 'delete_user'


  resources :trainings
  resources :weigths
  resources :measures
  resources :current_measures
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  has_many :weigths
  has_many :users
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!
  require 'will_paginate/array'

  def index
    @q = User.ransack(params[:query])
    @user_finder = @q.result
    @user_finder = @user_finder.paginate(page: params[:page], per_page: 10).order('username asc')
    @trainings  = Training.all
    @current_weigth = Weigth.order(created_at: :desc)
    @training_id = Training.order(created_at: :desc).last
    @length_weigth = 0
    if Weigth.all.length != 0
      Weigth.where(training_id: @training_id.id).each do
        @length_weigth += 1
      end
    end
  end

  def show
    @training = Training.where(user_id: current_user).map
    @current_weigth = Weigth.order(created_at: :desc)
    @training_id = Training.order(created_at: :desc).last
    @length_weigth = 0
    if !Weigth.all.length == 0
      Weigth.where(training_id: @training_id.id).each do
        @length_weigth += 1
      end
    end
  end

  def new
    @training = Training.new
  end

  def edit
    @training  = Training.find(params[:id])
  end

  def create
    @training = Training.new(training_params)
    @training.save
    respond_to do |format|
      if @training.save
        format.html { redirect_to trainings_looper_url, notice: "Treino salvo com sucesso!" }
        format.json { render :index, status: :ok, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @training = Training.find(params[:id])
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to trainings_path, notice: "Treino modificado com sucesso!" }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @training = Training.find(params[:id])
  end
  # DELETE /companies/1 or /companies/1.json
  def destroy
    @training = Training.find(params[:id])
    @weigth = Weigth.all
    respond_to do |format|
        @weigth.destroy_by(training_id: @training.id) if !@weigth.nil?
      @training.destroy
      format.html { redirect_to trainings_path, notice: "Treino deletado com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit( :user_id,  :weigth, :name_training)
    end

end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/trainings/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="form">
      <%= form_for @training do |form| %>
        <div class="box-form">
          <div class="form-content">
            <h3 class="titulo">Adicionar Peso</h3>

              <div class="form-input">
                <label for="name_training"> Treino <span>*</span></label>
                <%= form.text_field :name_training, autofocus: true, autocomplete: "name_training", class:'form_login', :required => true %>
              </div>
              <div class="form-input">
                  <label for="weigth"> Peso (em Kg) <span>*</span></label>
                  <%= form.number_field :weigth, step: :any, min: 1, autofocus: true, autocomplete: "weigth", class:'form_login', :required => true %>
              </div>
            <%= form.hidden_field :user_id, value: current_user.id.to_i %>
            <div class="actions">
              <%= form.submit 'Salvar', class:'button_login' %>
            </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/trainings/_search_form.html.erb
<br>
<%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
    <%= search_form_for(@q, url: "/trainings", method: :get) do |f| %>
        <div class="container-search">
            <%= f.search_field :username_cont, class: "field", :placeholder => "Nome do Usuário..." %>
            <%= image_submit_tag("search.png", class: "button-search") %>
        </div>
    <% end %>

app/views/trainings/_template_dropdown.html.erb
<h2 class="title is-4">Treinos</h2>
<%= render "search_form"%>
<% @user_finder.each do |s|%>
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn"><%= sort_link(@q, :name_training, s.username, default_order: :asc, class:"links-form") %></button>
    <div id="myDropdown" class="dropdown-content">
    <table class="tabelas_treino">
      <thead>
        <th>Frango</th>
        <th>Treino</th>
        <th>Peso Atual</th>
        <% @length_weigth.times do %>
          <th>Pesos Anteriores</th>
        <% end %>
      </thead>
      <tbody>
        <% @trainings.each do |t| %>
          <%  @user_name = User.find(t.user_id) %>
          <tr>
            <td><%= @user_name.username %></td>
            <td><%= t.name_training %></td>
            <td><%= t.weigth %></td>
            <% @counting = 0 %>
            <% @current_weigth.where(training_id: t.id).each do |w| %>
              <td><%= w.weigth %></td>
              <% @counting += 1 %>
            <% end %>
            <% i = @length_weigth - @counting %>
            <%i.times do %>
              <td>N/A</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
<% end %>
<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

app/views/trainings/edit.html.erb
<%= render "form", training: @training %>

app/views/trainings/index.html.erb
<!DOCTYPE html>
<html class="html">
  <%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
  <body class="body">
    <%= render "search_form"%>
    <div class= "center-table">
      <ul class="digg_pagination">
        <%= will_paginate(@user_finder)%>
      </ul>
      <table class="styled-table">
        <thead>
          <th><%= sort_link(@q, :username, "Frango", default_order: :asc, class:"links-form")%></th>
          <th>Treino</th>
          <th>Peso Atual</th>
          <% @length_weigth.times do %>
            <th>Pesos Anteriores</th>
          <% end %>
          <% if !current_user.nil? %>
            <th>Alterar Ultimo Peso</th>
            <th>Deletar Treino</th>
          <% end %>
        </thead>
        <tbody class="tbody-form">
          <% @user_finder.each do |u| %>
            <% @user_finder = Training.where(user_id: u.id ) %>
            <% @user_finder.each do |t| %>
              <% @user_name = User.find(t.user_id).username %>
              <tr>
                <td><%= @user_name %></td>
                <td><%= t.name_training %></td>
                <td><%= t.weigth %></td>
                <% @counting = 0 %>
                <% @current_weigth.where(training_id: t.id).each do |w| %>
                  <td><%= w.weigth %></td>
                  <% @counting += 1 %>
                <% end %>
                <% i = @length_weigth - @counting %>
                <%i.times do %>
                  <td>N/A</td>
                <% end %>
                <% if current_user.username == @user_name %>
                  <td> <%= link_to "Editar", edit_training_path(t.id) %> </td>
                  <td> <%= link_to "Deletar",trainings_delete_path(t.id) %> </td>
                <% else %>
                  <td>Não é seu usuário!</td>
                  <td>Não é seu usuário!</td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/trainings/looper.html.erb
<h1 class="title">A princesa deseja adicionar mais algum treino?</h1>
<div class="nav-bar-item">
    <%= link_to "Sim", new_training_path, class: "button" %>
    <%= link_to "Não", root_path, class: "button" %>
</div>

app/views/trainings/new.html.erb
<%= render "form", training: @training %>

app/views/trainings/show.html.erb
<!DOCTYPE html>
<html class="html">
    <%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
    <body class="body">
        <form>
            <section id="content">
                <h3>Wtf</h3>
                <p>O que krls tu ta fznd aqui???????</p>

                <h3>Bom, já q tu ta aqui,  veja: </h3>
                <ul>
                <li><%= link_to "Rafael de bikini", "https://www.youtube.com/watch?v=dQw4w9WgXcQ" %></li>
                <li><%= link_to "Big Hard Paul", "https://www.youtube.com/@paulodurao9426" %></li>
                <li><%= link_to "Como mandar felipe e ollie", "https://www.youtube.com/watch?v=0nCyevYbtM8" %></li>
                </ul>
                <h3>FRASE DO DIA:</h3>
                <p>NANDO GAY</p>
            </section>
        </form>

        <footer>
            <p>&copy; 2023 Olympia Tribess. Todos os direitos reservados.</p>
        </footer>

        <%= javascript_include_tag('application.js') %>
    </body>
</html>