config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  root 'home#index'
  get 'trainings/looper'
  get 'measures/looper'
  delete 'trainings/:id/delete' => 'trainings#destroy', as: 'trainings_delete'
  get '/trainings/:id/delete' => 'trainings#destroy'
  delete 'measures/:id/delete' => 'measures#destroy', as: 'measures_delete'
  get '/measures/:id/delete' => 'measures#destroy'
  get '/trainings/:id/edit' => 'trainings#edit'
  post '/trainings/:id/edit' => 'trainings#update'
  get '/pages/sobre' =>  'sobre'
  get '/pages/regras' =>  'regras'
  get '/users/passwords/new' => 'users#new', as: 'forgot_password'
  delete '/users/registrations/:id/delete' => 'users#destroy', as: 'delete_user'


  resources :trainings
  resources :weigths
  resources :measures
  resources :current_measures
end

app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :user
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController

  def index
    @q = User.ransack(params[:query])
    @user_finder = @q.result.paginate(page: params[:page], per_page: 10).order('username asc')
    @measures  = Measure.all
    @current_measure = CurrentMeasure.order(created_at: :desc)
  end
  def show
  end

  def new
    @measure = Measure.new
  end
  def edit
    @measure = Measure.find(params[:id])
  end


  def update
    @measure = Measure.find(params[:id])
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to measures_path, notice: "Medida modificada com sucesso!" }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end


  def delete
    @measure = Measure.find(params[:id])
  end

  def destroy
    @measure = Measure.find(params[:id])
    @current_measure = CurrentMeasure.all
    respond_to do |format|
        @current_measure.destroy_by(measure_id: @measure.id) if !@current_measure.nil?

      @measure.destroy
      format.html { redirect_to measures_path, notice: "Medida deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to measures_looper_url}
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def measure_params
    params.require(:measure).permit( :new_measure, :name_muscle, :user_id)
  end

end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/measures/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="form">
      <%= form_for @measure do |form| %>
        <div class="box-form">
          <div class="form-content">
            <h3 class="titulo">Adicionar Medida</h3>
            <div class="form-input">
              <label for="name_muscle"> Músculo <span>*</span></label>
              <%= form.text_field :name_muscle, step: :any, autofocus: true, autocomplete: "name_muscle", class:'form_login', :required => true %>
            </div>
            <div class="form-input">
                <label for="new_measure"> Medida (em cm) <span>*</span></label>
                <%= form.number_field :new_measure, step: :any, min: 1, autofocus: true, autocomplete: "weigth", class:'form_login', :required => true %>
            </div>
            <%= form.hidden_field :user_id, value: current_user.id.to_i %>
            <div class="actions">
              <%= form.submit 'Salvar', class:'button_login' %>
            </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/measures/_search_form.html.erb
<%= search_form_for(@q, url: "/measures", method: :get) do |f| %>
          <div class="container-search">
              <%= f.search_field :username_cont, class: "field", :placeholder => "Nome do Usuário..." %>
              <%= image_submit_tag("search.png", class: "button-search") %>
          </div>
      <% end %>

app/views/measures/edit.html.erb
<%= render "form", measure: @measure %>

app/views/measures/index.html.erb
<!DOCTYPE html>
<html class="html">
  <%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
  <body class="body">
    <br>
      <%= render "search_form" %>
    <div class="center-table">
        <ul class="digg_pagination">
          <%= will_paginate(@user_finder)%>
        </ul>
      <table class="styled-table">
        <thead>
          <th>Frango</th>
          <th>Área</th>
          <th>Medida Atual</th>
          <% @current_measure.each do %>
          <th>Medidas Anteriores</th>
          <% end %>
          <% if !current_user.nil? %>
            <th>Alterar Ultima Medida</th>
            <th>Deletar Medida</th>
          <% end %>
        </thead>
        <tbody class="tbody-form">
          <% @user_finder.each do |u| %>
            <% @user_finder = Measure.where(user_id: u.id ) %>
            <% @user_finder.each do |m| %>
              <% @user_name = User.find(m.user_id).username %>
              <tr>
                <td><%= @user_name %></td>
                <td><%= m.name_muscle %></td>
                <td><%= m.new_measure %></td>
                <% @current_measure.each do |w| %>
                <td><%= w.measure_new %></td>
                <% end %>
                <% if current_user.username == @user_name %>
                  <td> <%= link_to "Editar", edit_measure_path(m.id) %> </td>
                  <td> <%= link_to "Deletar", measures_delete_path(m.id) %> </td>
                <% else %>
                  <td>Não é seu usuário!</td>
                  <td>Não é seu usuário!</td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/measures/looper.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="form">
        <div class="box-form">
            <div class="form-content">
                <h3 class="titulo">A Princesa deseja adicionar uma nova medida?</h3>
                <div class="form-input">
                    <%= link_to "Sim", new_measure_path, class: 'button-looper' %>
                    <br>
                    <%= link_to "Não", measures_path, class: 'button-looper' %>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>

app/views/measures/new.html.erb
<%= render "form", measure: @measure %>

app/views/measures/show.html.erb
<!DOCTYPE html>
<html class="html">
    <%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
    <body class="body">
        <form>
            <section id="content">
                <h3>Wtf</h3>
                <p>O que krls tu ta fznd aqui???????</p>

                <h3>Bom, já q tu ta aqui,  veja: </h3>
                <ul>
                <li><%= link_to "Rafael de bikini", "https://www.youtube.com/watch?v=dQw4w9WgXcQ" %></li>
                <li><%= link_to "Big Hard Paul", "https://www.youtube.com/@paulodurao9426" %></li>
                <li><%= link_to "Como mandar felipe e ollie", "https://www.youtube.com/watch?v=0nCyevYbtM8" %></li>
                </ul>
                <h3>FRASE DO DIA:</h3>
                <p>NANDO GAY</p>
            </section>
        </form>

        <footer>
            <p>&copy; 2023 Olympia Tribess. Todos os direitos reservados.</p>
        </footer>

        <%= javascript_include_tag('application.js') %>
    </body>
</html>