config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  root 'home#index'
  get 'trainings/looper'
  get 'measures/looper'
  delete 'trainings/:id/delete' => 'trainings#destroy', as: 'trainings_delete'
  get '/trainings/:id/delete' => 'trainings#destroy'
  delete 'measures/:id/delete' => 'measures#destroy', as: 'measures_delete'
  get '/measures/:id/delete' => 'measures#destroy'
  get '/trainings/:id/edit' => 'trainings#edit'
  post '/trainings/:id/edit' => 'trainings#update'
  get '/pages/sobre' =>  'sobre'
  get '/pages/regras' =>  'regras'
  get '/users/passwords/new' => 'users#new', as: 'forgot_password'
  delete '/users/registrations/:id/delete' => 'users#destroy', as: 'delete_user'


  resources :trainings
  resources :weigths
  resources :measures
  resources :current_measures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current_measure.rb
class CurrentMeasure < ApplicationRecord
  belongs_to :measure
end

app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :user
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  has_many :weigths
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        def self.ransackable_associations(auth_object = nil)
        []
        end
        def self.ransackable_attributes(auth_object = nil)
        ["username"]
      end
end

app/models/weigth.rb
class Weigth < ApplicationRecord
  belongs_to :training
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController

  def index
    @q = User.ransack(params[:query])
    @user_finder = @q.result.paginate(page: params[:page], per_page: 10).order('username asc')
    @measures  = Measure.all
    @current_measure = CurrentMeasure.order(created_at: :desc)
  end
  def show
  end

  def new
    @measure = Measure.new
  end
  def edit
    @measure = Measure.find(params[:id])
  end


  def update
    @measure = Measure.find(params[:id])
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to measures_path, notice: "Medida modificada com sucesso!" }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end


  def delete
    @measure = Measure.find(params[:id])
  end

  def destroy
    @measure = Measure.find(params[:id])
    @current_measure = CurrentMeasure.all
    respond_to do |format|
        @current_measure.destroy_by(measure_id: @measure.id) if !@current_measure.nil?

      @measure.destroy
      format.html { redirect_to measures_path, notice: "Medida deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to measures_looper_url}
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def measure_params
    params.require(:measure).permit( :new_measure, :name_muscle, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def sobre
  end
  def regras
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!
  require 'will_paginate/array'

  def index
    @q = User.ransack(params[:query])
    @user_finder = @q.result
    @user_finder = @user_finder.paginate(page: params[:page], per_page: 10).order('username asc')
    @trainings  = Training.all
    @current_weigth = Weigth.order(created_at: :desc)
    @training_id = Training.order(created_at: :desc).last
    @length_weigth = 0
    if Weigth.all.length != 0
      Weigth.where(training_id: @training_id.id).each do
        @length_weigth += 1
      end
    end
  end

  def show
    @training = Training.where(user_id: current_user).map
    @current_weigth = Weigth.order(created_at: :desc)
    @training_id = Training.order(created_at: :desc).last
    @length_weigth = 0
    if !Weigth.all.length == 0
      Weigth.where(training_id: @training_id.id).each do
        @length_weigth += 1
      end
    end
  end

  def new
    @training = Training.new
  end

  def edit
    @training  = Training.find(params[:id])
  end

  def create
    @training = Training.new(training_params)
    @training.save
    respond_to do |format|
      if @training.save
        format.html { redirect_to trainings_looper_url, notice: "Treino salvo com sucesso!" }
        format.json { render :index, status: :ok, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @training = Training.find(params[:id])
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to trainings_path, notice: "Treino modificado com sucesso!" }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @training = Training.find(params[:id])
  end
  # DELETE /companies/1 or /companies/1.json
  def destroy
    @training = Training.find(params[:id])
    @weigth = Weigth.all
    respond_to do |format|
        @weigth.destroy_by(training_id: @training.id) if !@weigth.nil?
      @training.destroy
      format.html { redirect_to trainings_path, notice: "Treino deletado com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit( :user_id,  :weigth, :name_training)
    end

end

app/controllers/weigths_controller.rb
class WeigthsController < ApplicationController
  def new

  end
  def create
    @current_weigth = Training.find(training_find["training_id"])
    @weigth = Training.where(id: @current_weigth).update(training_params)
    @new_weigth = Weigth.new(weigth: @current_weigth.weigth , training_id: training_find["training_id"])


    respond_to do |format|
      if @new_weigth.save
        format.html { redirect_to trainings_url}
        format.json { render :show, status: :created, location: @weigth }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weigth.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def training_find
    params.require(:weigth).permit( :training_id)
  end
  def training_params
    params.require(:weigth).permit( :weigth)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_measures_helper.rb
module CurrentMeasuresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/helpers/weigths_helper.rb
module WeigthsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
    <nav class="nav">
        <ul>
            <li>
                <div>
                    <a href="/" class="image_logo" ><%= image_tag "brazil_flag.png", class: "image_logo"%></a>
                </div>
            </li>
            <li>
                <% if !current_user.nil?%>
                    <a class="navbar-item">Usuário Logado: <%= current_user.username %></a>
                <% else %>
                    <a class="navbar-item">Usuário Logado: Nenhum</a>
                <% end %>
            </li>
        </ul>
        <ul>
            <li><a>TREINOS</a>
                <div class="submenu">
                    <ul>
                        <li class="hover-sub"><%= link_to "EVOLUÇÃO", trainings_path %></li>
                        <li><%= link_to "REGISTRAR TREINO", new_training_path %></li>
                        <li><%= link_to "ADICIONAR PESO"  , new_weigth_path %></li>
                    </ul>
                </div>
            </li>
            <li><a>MEDIDAS</a>
                <div class="submenu">
                    <ul>
                        <li class="hover-sub"><%= link_to "EVOLUÇÃO",  measures_path %></li>
                        <li><%= link_to "REGISTRAR MEDIDA", new_measure_path %></li>
                        <li><%= link_to "REGISTRAR NOVA MEDIDA", new_current_measure_path %></li>
                    </ul>
                </div>
            </li>
            <li><a>CONFIG.</a>
                <div class="submenu">
                    <ul>
                        <li><%= link_to "LOGIN", new_user_session_path %></li>
                        <li><%= link_to "LOGOUT",destroy_user_session_path, 'data-turbo-method': :delete %></a></li>
                    </ul>
                </div>
            </li>
            <li><a>SOBRE</a>
                <div class="submenu">
                    <ul>
                        <li><%= link_to "CONHEÇA O PROJETO", pages_sobre_path %></li>
                        <li><%= link_to "REGRAS", pages_regras_path %></li>
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MrOympia Tribess</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "applications", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <% if notice %>
        <p class="success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="error"><%= alert %></p>
      <% end %>
      <section class="section">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/regras.html.erb
<!DOCTYPE html>
<html>
    <body class="body">
        <form>
            <section id="content">
                <h3>Regras</h3>
                <p>Aqui está listado algumas das regras que seria bom ser seguidas:</p>

                <ul>
                    <li>Comprometimento com o gerenciamento dos seus resultados</li>
                    <li>Não mentir pesos (supino com 900kg) </li>
                    <li>Não zuar o FAQ do site</li>
                    <li>Não postar merda no site</li>
                    <li>Não tentar derrubar o site, pls</li>
                </ul>
            </section>
        </form>
    </body>
</html>

app/views/pages/sobre.html.erb
<!DOCTYPE html>
<html>
    <body class="body">
        <form>
            <section id="content">
                <p>O Projeto Olympia é um site cirado para podermos postar nossa evolução, dicas, indicar musicas e playlist's. O projeto consiste em 3 meses de foco intenso na academia, alimentação e dedicação a tudo que possa oferecer resultados positivos. Aqui iremos mostrar os treinos que faremos diariamente juntamente com as medidas, assim tendo maior noção da evolução que estamos tendo.
                Recomendamos ler as regras no meunu "SOBRE" para não ter erros!
                Ele esta sendo criado por Mac_Raff & Vmp e vamos estar sempre abertos a novas ideias para a melhoria do site e do projeto! #Soldados do Breier </p>
            </section>
        </form>
    </body>
</html>